config/routes.rb
Rails.application.routes.draw do
  get 'redis/index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get 'sessions/new'
  get 'users/new'
  root 'posts#index'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  get "redis", to: "redis#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    # @post.comments で引っ張ってこれる
    validates :title, presence: true, length: {minimum: 3, message: 'Too short to post!'}
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email=email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    if remember_digest.nil?
      return false
    end
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private
        def comment_params
            params.require(:comment).permit(:body)
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all.order(created_at: 'desc')
        ids = REDIS.zrevrangebyscore "ranking", "+inf", 0, limit: [0, 3]
        @ranking_posts = ids.map{ |id| Post.find(id) }
        # debugger
        if @ranking_posts.count < 3
            adding_posts = Post.order(published_at: :DESC, updated_at: :DESC).where.not(id: ids).limit(3 - @ranking_posts.count)
            @ranking_posts.concat(adding_posts)
        end
    end

    def show
        @post = Post.find(params[:id])
        REDIS.zincrby "ranking", 1, @post.id
    end

    def new
        @post = Post.new
        # @user = User.find(params[:id])
    end

    def create
        # 送信されたデータが post をキーにして title と body があるハッシュかどうかを確認
        @post = Post.new(post_params)
        @post[:user_id] = current_user[:id]
        # debugger
        # validation に引っかからない場合
        if @post.save
            # redirect
            redirect_to posts_path
        else
            # エラーメッセージの表示
            # render plain: @post.errors.inspect
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
        unless @post[:user_id] == current_user[:id]
            # flash.now[:danger] = "#{@post[:user_id]}, #{current_user[:id]}"
            redirect_to(root_url)
            flash[:danger] = 'This is not your post'
        end
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        unless @post[:user_id] == current_user[:id]
            # flash.now[:danger] = "#{@post[:user_id]}, #{current_user[:id]}"
            redirect_to(root_url)
            flash[:danger] = 'This is not your post'
        else
            @post.destroy
            redirect_to posts_path
        end
    end

    private
        def post_params
            params.require(:post).permit(:title, :body)
        end
    
end

app/controllers/redis_controller.rb
class RedisController < ApplicationController
  def index
    Redis.current.set("testkey", "mebee")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にrootにリダイレクトする
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or root_path
    else
      # エラーメッセージを作成
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private 
    def user_params
      params.require(:user).permit(:email, :password,
        :password_confirmation)
    end

    # beforeアクション
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to(root_url)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/redis_helper.rb
module RedisHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  # 現在ログイン中のユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif(user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module  UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer_inner">
    <p>Copyright RailsCamp 2015 All Rights Reserved</p>
</div>

app/views/layouts/_header.html.erb
<head>

<p id="logo"><a href="/">RailsCamp<span>Blog</span></a></p>
<nav>
    <ul>
        <li><%= link_to 'トップ', root_path %></li>
        <% if logged_in? %>
            <li><%= link_to '新規投稿', new_post_path %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
        <div class="clear"></div>
    </ul>
</nav>
<div class="clear"></div>
</head>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<h2>★PV数ランキング</h2>
<ul>
    <% @ranking_posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %><span> (<%= REDIS.zscore("ranking", post.id).to_i %>PV) </span></li>
    <% end %>
</ul>

app/views/layouts/_title.html.erb
<meta charset="UTF-8">
<title>Rails Camp Blog</title>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "style", :media => "all" %>
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/rails_default'%>
    <%= render 'layouts/shim' %>
  </head>

  <body>

    <header>
      <%= render "layouts/header" %>
    </header>

    <div id="main">
      <p><%= image_tag("main-img.jpg", alt: "main") %></p>
    </div>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <div id="article_wrap">
      <%= yield %>
      <div class="clear"></div>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>


    <footer>
      <%= render 'layouts/footer' %>
    </footer>


  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%# タイトルを入力してもらうもの、一行テキストはf.text_field %>
<p>
    <%= f.text_field :title, placeholder: 'enter title'%>
    <% if @post.errors.messages[:title].any? %>
    <span class="error"><%= @post.errors.messages[:title][0] %></span>
    <% end %>
</p>
<%# 本文を入力するもの。複数行テキストは f.text_area %>
<p>
    <%= f.text_area :body, placeholder: 'enter body text'%>
    <% if @post.errors.messages[:body].any? %>
    <span class="error"><%= @post.errors.messages[:body][0] %></span>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<div id="article_wrap">
    <div id="article_list">
        <% @posts.each do |post| %>
            <div>
                <h2><%= link_to post.title, post_path(post) %></h2>
                <p><%= l post.updated_at %></p>
                <% if logged_in? %>
                    <%= link_to '編集', edit_post_path(post), class: 'command'%>
                    <%= link_to '削除',
                        post_path(post), 
                        method: :delete,
                        class: 'command',
                        data: { confirm: 'Sure??'} %>
                <% end %>
            </div>
        <% end %>
    </div>
    <div id="sidebar">
        <%= render "layouts/sidebar" %>
    </div>
</div>

app/views/posts/new.html.erb
<h2>Add New Post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= simple_format @post.body %></p>

app/views/redis/index.html.erb
<h1>Redis#index</h1>
<p>Find me in app/views/redis/index.html.erb</p>
<%= Redis.current.get("testkey") %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/login.html.erb
<h1>ログイン</h1>
<%= form_for(:session, url: login_path) do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.submit "Log in" %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%=  render 'shared/error_messages' %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Sign up", class: "btn btn-primary" %>
        <%= link_to 'Log in', '#' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>